services:
  db:
    image: mysql:8.0
    container_name: ait_db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: ait_backend
    restart: unless-stopped
    environment:
      DJANGO_SECRET_KEY: "change-me"
      DJANGO_DEBUG: "1"
      ALLOWED_HOSTS: "*"
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: app
      DB_HOST: db
      DB_PORT: "3306"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ait_frontend
    environment:
      VITE_API_URL: "http://localhost:8000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host"
